### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [OlgaLavrishcheva/Kinozal#1]
1)
что у вас здесь с форматирование кода?
![image](https://user-images.githubusercontent.com/8464662/119647572-1a5a6380-be29-11eb-8030-ddcaaf965e24.png)

2)
наведение не отрабатывает
![image](https://user-images.githubusercontent.com/8464662/119647631-2d6d3380-be29-11eb-8761-f24e90f3224d.png)

3)
поля не должны обрываться
![image](https://user-images.githubusercontent.com/8464662/119647832-6a392a80-be29-11eb-8837-c6f7be924bd9.png)

**Comment by OlgaLavrishcheva** [comment]
Проработаны. Коммит "работа над ошибками #1"

**Comment by Alecto** [comment]
и 2 ссылочки, у меня их нет

ср, 26 мая 2021 г. в 16:12, OlgaLavrishcheva ***@***.***>:
